name: Sync

on:
  push:

  schedule:
  - cron: "0 23 * * *"

jobs:
  sync:
    name: Sync ${{ matrix.repo }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: [openwrt/openwrt, openwrt/packages, openwrt/luci, qbittorrent/qBittorrent, hanwckf/rt-n56u, hanwckf/mt7615]
    steps:
      - name: Check the Source
        id: check-src
        run: |
          remoteRefs=$(git ls-remote ${GITHUB_SERVER_URL}/${{ matrix.repo }}.git refs/heads/*)
          remoteHash=$(echo "$remoteRefs" | cut -f1 | sed ':tag;N;$!b tag;s/\n/-/g')
          branches=$(echo "$remoteRefs" | cut -f2 | sed 's/\s*refs\/heads\///g')
          myHash=
          for br in $branches; do
          	mh="$(git ls-remote ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY_OWNER}/$(basename ${{ matrix.repo }}).git refs/heads/${br} | cut -f1)"
          	[ -n "${myHash}" ] && [ -n "$mh" ] && myHash="${myHash}-${mh}"
          	[ -z "${myHash}" ] && [ -n "$mh" ] && myHash="${mh}"
          done
          [ "$remoteHash" != "$myHash" ] && update=1 || update=0
          echo "update=${update}" >> $GITHUB_OUTPUT
          echo "hash=$(echo ${remoteHash} | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache Repo
        if: steps.check-src.outputs.update == '1'
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ matrix.repo }}
          key: source-${{ matrix.repo }}-${{ steps.check-src.outputs.hash }}
          restore-keys: |
            source-${{ matrix.repo }}-
      - name: Sync with Source
        if: steps.check-src.outputs.update == '1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          [ -e "${{ matrix.repo }}/.git" ] || git clone ${GITHUB_SERVER_URL}/${{ matrix.repo }} ${{ matrix.repo }}

          cd ${{ matrix.repo }}
          [ -z "$(git remote -v | grep "git://")" ] || git config --local url.${GITHUB_SERVER_URL}/.insteadOf git://github.com/

          git fetch origin --prune

          repo_name=$(basename ${{ matrix.repo }})
          [ -n "$(git remote | grep own)" ] && git remote remove own
          git remote add own https://${GITHUB_REPOSITORY_OWNER}:${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY_OWNER}/${repo_name}.git

          branches=$(git branch -a | grep -E '^\s+remotes/origin' | grep -v "remotes/origin/HEAD" | sed 's/\s*remotes\/origin\///g')
          default_branch="$(basename $(git symbolic-ref refs/remotes/origin/HEAD))"

          for branch in ${branches}; do
          	git switch -C "$branch" "origin/$branch"
          	git push own $branch
          done
          git remote remove own
          git switch "$default_branch"
