name: Sync

on:
  push:

  schedule:
  - cron: "0 23 * * *"

jobs:
  sync:
    name: Sync ${{ matrix.repo }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: [openwrt/openwrt, openwrt/packages, openwrt/luci, qbittorrent/qBittorrent, hanwckf/rt-n56u, hanwckf/mt7615]
    steps:
      - run: |
          hash="$(git ls-remote git://github.com/${{ matrix.repo }}.git HEAD | cut -f 1)"
          echo "::set-env name=hash::${hash}"
      - name: Cache Repo
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ matrix.repo }}
          key: source-${{ matrix.repo }}-${{ env.hash }}
          restore-keys: |
            source-${{ matrix.repo }}-
      - name: Clone Original Codes
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          [ -e "${{ matrix.repo }}/.git" ] || hub clone ${{ matrix.repo }} ${{ matrix.repo }}
      - name: Pull original codes
        id: pull
        env:
          GITHUB_TOKEN: ${{ secrets.SUPER_TOKEN }}
        run: |
          cd ${{ matrix.repo }}
          hub sync
          head="$(git rev-parse HEAD)"
          [ "${{ steps.cache.outputs.cache-hit }}" = "true" ] && [ "${{ env.hash }}" = "$head" ] && update=0 || update=1
          echo "::set-output name=update::${update}"
      - name: Push to Self Repo
        if: steps.pull.outputs.update == '1'
        env:
          GITHUB_TOKEN: ${{ secrets.SUPER_TOKEN }}
        run: |
          cd ${{ matrix.repo }}
          [ -n "$(git remote | grep own)" ] && git remote remove own
          repo_name=$(basename ${{ matrix.repo }})
          git remote add own https://brvphoenix:${{ secrets.SUPER_TOKEN }}@github.com/brvphoenix/${repo_name}.git
          hub push own "$(basename $(git symbolic-ref refs/remotes/origin/HEAD))"
          git remote remove own
